package com.yuxiu.edu.model;

import java.util.Date;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.id
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.name
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.depno
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    private String depno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.createtime
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.build_date
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    private Date buildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.pid
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.id
     *
     * @return the value of t_department.id
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.id
     *
     * @param id the value for t_department.id
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.name
     *
     * @return the value of t_department.name
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.name
     *
     * @param name the value for t_department.name
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.depno
     *
     * @return the value of t_department.depno
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public String getDepno() {
        return depno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.depno
     *
     * @param depno the value for t_department.depno
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public void setDepno(String depno) {
        this.depno = depno == null ? null : depno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.createtime
     *
     * @return the value of t_department.createtime
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.createtime
     *
     * @param createtime the value for t_department.createtime
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.build_date
     *
     * @return the value of t_department.build_date
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public Date getBuildDate() {
        return buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.build_date
     *
     * @param buildDate the value for t_department.build_date
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public void setBuildDate(Date buildDate) {
        this.buildDate = buildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.pid
     *
     * @return the value of t_department.pid
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.pid
     *
     * @param pid the value for t_department.pid
     *
     * @mbggenerated Mon Jun 04 22:04:46 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}